<a href="https://colab.research.google.com/github/Ishanthedev/Python/blob/master/Python_Refresher_for_AI_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np




In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [0]:
a = np.array([[1,2,3],[2,3,4]])

In [12]:
a = np.array([1,2,3],dtype='int64')
print(a)
a.itemsize #tell us the bit size
a.ndim
a.nbytes #tell us the byte

[1 2 3]


24

In [20]:
a =np.array([1,2,3,4,5,6,7,8,9,10])
v=a[2:4]
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
np.ones((4,4),dtype ='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [23]:
np.zeros((4,4),dtype ='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [26]:
np.full((5,5),'100')

array([['100', '100', '100', '100', '100'],
       ['100', '100', '100', '100', '100'],
       ['100', '100', '100', '100', '100'],
       ['100', '100', '100', '100', '100'],
       ['100', '100', '100', '100', '100']], dtype='<U3')

In [27]:
#everything has to began with array
a=np.array([[[1,2,3]]])
a.ndim

3

In [40]:
a=np.full((5,5),10)
print(a)
#a[:4]=5

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [41]:
b= np.full((2,2),5)
print(b)

a[2:4,2:4] =b # merging two arrays into one
print(a)

[[5 5]
 [5 5]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10  5  5 10]
 [10 10  5  5 10]
 [10 10 10 10 10]]


In [48]:
np.random.rand(4,2)# random array 


array([[0.44121594, 0.73788771],
       [0.20810073, 0.9784263 ],
       [0.16172492, 0.6510443 ],
       [0.85492921, 0.89560664]])

In [49]:
np.identity(5)# identity matrix


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,3,axis = 0) # axis = 0 will orient the array vertically
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
r2 = np.repeat(ar,3,axis = 1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


In [61]:
a=np.full((5,5),10)
print(a)
b= np.full((3,3),0)
print(b)

a[2:3:3,2:3:3] =b
print(a)


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


ValueError: ignored

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [65]:
np.sin(a)

array([[-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111]])

In [73]:
k= np.full((3,3),10)
np.linalg.det(k) # determinant

0.0

In [74]:
k[1,2]=19
k[1,1]=9
print(k)
np.linalg.det(k)

[[10 10 10]
 [10  9 19]
 [10 10 10]]


0.0

In [76]:
np.max(k)
np.max(k,axis = 0)# getting the matrix

array([10, 10, 19])

In [80]:
v1 = np.array([1,2,3,45,6])
v2 = np.array([2,3,100,42,6])
np.vstack([v1,v2])#stacked v1 upon v2
np.vstack([v2,v1])#stacked v2 upon v1

array([[  2,   3, 100,  42,   6],
       [  1,   2,   3,  45,   6]])

In [0]:
filedata = np.genfromtxt('data.txt',delimter = ',') #file getting delimted by ','


In [0]:
import pandas as pd

In [84]:
data = pd.Series([0.25,0.5,0.75,1.0]) #indexed already
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [88]:
data.values #shows you the vlaues of the series

array([0.25, 0.5 , 0.75, 1.  ])

In [93]:
data.index


RangeIndex(start=0, stop=4, step=1)

In [95]:
data = pd.Series([0.25,0.5,0.75,1.0], index =['a','b','c','d']) # giving the index of as per our need
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [98]:
data = pd.Series({'California': 67893473,'Texas': 233433,'New Youk': 234334424,'Florida': 1232434})
data['California':'Texas']# slicing

California    67893473
Texas           233433
dtype: int64

In [99]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [100]:
area = pd.Series({'California': 67893473,'Texas': 233433,'New Youk': 234334424,'Florida': 1232434})
states = pd.DataFrame({'Population': data,'area':area}) #making a dataframe 
states

Population       area
California    67893473   67893473
Texas           233433     233433
New Youk     234334424  234334424
Florida        1232434    1232434

In [103]:
states['area'] # way 1 of gettind the data from the dataframe
states.area # way 2 of gettind the data from the dataframe

California     67893473
Texas            233433
New Youk      234334424
Florida         1232434
Name: area, dtype: int64

In [105]:
#list comprehension to generatre dynamic data frames
data =[{'a':1,'b':2*1} for i in range(3)]
pd.DataFrame(data)

a  b
0  1  2
1  1  2
2  1  2

In [106]:
#Pandas putting nans in the missing values
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])


a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [107]:
pd.DataFrame({'a':1,'b':2},{'b':3,'c':4})

a  b
b  1  2
c  1  2

In [109]:
#index in pandas Index objects are immutable
ind=pd.Index([[2,3,5,7,11]])
ind

Index([[2, 3, 5, 7, 11]], dtype='object')

In [110]:
ind1 = pd.Index([1,3,5,6,9])
ind2 = pd.Index([2,3,5,7,11])
ind1 & ind2
ind1 | ind2
ind1 ^ ind2

Int64Index([1, 2, 6, 7, 9, 11], dtype='int64')

In [114]:
data1=pd.Series([0.24,0.5,0.75,1.0], index=['a','f','y','r'])
print(data1)

a    0.24
f    0.50
y    0.75
r    1.00
dtype: float64


In [116]:
data1[(data1>0.3) & (data1 < 0.8)]

f    0.50
y    0.75
dtype: float64

In [126]:
data = pd.Series([0.25,0.5,0.75,1.0], index=[1,2,3,4]) #explict index
data
#data.loc[1]#explicit index what is mentioned in the index above
data.iloc[2]#implict like starting from 0,1,2

0.75

In [128]:
Population = pd.Series({'California': 67893473,'Texas': 233433,'New Youk': 234334424,'Florida': 1232434})

data = pd.DataFrame({'area': area, 'pop': Population})
data

area        pop
California   67893473   67893473
Texas          233433     233433
New Youk    234334424  234334424
Florida       1232434    1232434